---
namespace: community
name: memsource
version: 0.0.1
readme: README.md

authors:
  - Yanis Guenane <yguenane+opensource@gmail.com>

description: An Ansible collection to interact with Memsource

license:
  - Apache-2.0
license_file: LICENSE

tags:
  - memsource
  - translation
  - localization

dependencies: {}

repository: https://github.com/ansible/ansible.memsource
documentation: https://github.com/ansible/ansible.memsource
homepage: https://github.com/ansible/ansible.memsource
issues: https://github.com/ansible/ansible.memsource/issues
